name: flora-dev

services:
  # ollama:
  #   volumes:
  #     - ollama:/root/.ollama
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: always
  #   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  frontend:
    build:
      context: .
      target: build
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json

  backend:
    build:
      context: .
      target: base
    command: ["bash", "dev.sh"]
    depends_on:
      - db
    env_file: ".env"
    environment:
     - ENV=dev
     - WEBUI_AUTH=False
     - WEBUI_SECRET_KEY="development"
     - DATABASE_URL=postgresql://postgres:password!@db:5432/postgres
     - GLOBAL_LOG_LEVEL=DEBUG
    volumes:
      - data:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - backend/data
        - action: rebuild
          path: backend/requirements.txt
  

  db:
    image: postgres:16-alpine
    # set shared memory limit when using docker-compose
    ports:
      - 5432:5432
    volumes:
      - flora-pg:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password!

volumes:
  flora-pg: {}
  data: {}
  ollama: {}