name: Build and Push to ECR

on:
  push:
    branches:
      - main  # You can adjust this to match your target branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up AWS credentials from GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

          # Extract GitHub repository name (use repo_name for ECR)
      - name: Extract repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV


      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names "${{ env.REPO_NAME }}-${{ github.ref_name }}" || \
          aws ecr create-repository --repository-name "${{ env.REPO_NAME }}-${{ github.ref_name }}" \
          --image-scanning-configuration scanOnPush=true \
          --encryption-configuration encryptionType=AES256

    #   # Build, tag, and push image to ECR
    #   - name: Build, tag, and push image to ECR
    #     env:
    #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #       REPOSITORY_NAME: ${{ env.REPO_NAME }}
    #       COMMIT_SHA: ${{ github.sha }}
    #       IMAGE_BRANCH: ${{ github.ref_name }}
    #     run: |
    #       # Build the Docker image
    #       docker build -t $REPOSITORY_NAME-$IMAGE_BRANCH:$COMMIT_SHA .

    #       docker push $REPOSITORY_NAME-$IMAGE_BRANCH:$COMMIT_SHA
    #       docker push $REPOSITORY_NAME-$IMAGE_BRANCH:latest

        
      - run: docker build --tag ${{ env.REPO_NAME }}-${{ github.ref_name }}:${{ github.sha }} .
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v2
        with:
            access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            region: eu-central-1
            local-image: ${{ env.REPO_NAME }}-${{ github.ref_name }}:${{ github.sha }}
            image: ${{ env.REPO_NAME }}-${{ github.ref_name }}:${{ github.sha }}, ${{ env.REPO_NAME }}-${{ github.ref_name }}:latest